- swarm-private/templates/swarm.statefulset.yaml
- swarm-private/values.yaml
- Removing an unused variable
- Removing .Release.Namespace from DNS name since it's not needed when running pods in the same namespace
> swarm-private: small fixes

- .gitignore
- .travis.yml
- Makefile
- package.sh
This PR improves the helm repo index generation because now it takes in consideration the previously existing `index.yaml`. Previously it was updating the timestamps of existing charts even when there were no changes to them.
Additionally, I've added a `Makefile` that for now is mainly used for linting (helm lint + shellcheck). This  made the CI scripts smaller because now it only needs to call `make lint`.
> Better generation for the `index.yaml` when executing "helm repo index"

- swarm-private/templates/smoke.cronjob.yaml
- swarm-private/values.yaml
- swarm/values.yaml
This PR is adding a CronJob to the `swarm-private` chart, which when enabled with run `swarm-smoke` tests on the given deployment.
Also updates the location of our Grafana dashboards.
> swarm-private: add smoke test cron job

- swarm-private/templates/swarm.statefulset.yaml
Currently it's using the host IP address, instead it should use the pod IP address.
I also tried setting `-nat=none` because all our swarm pods belong to the same network (LAN), therefore it doesn't make sense to talk about NAT. But this was still setting the enodes IP address to 127.0.0.1.
> swarm-private: use pod IP on nat flag

- swarm-private/templates/swarm.ingress.yaml
- swarm-private/values.yaml
- swarm/templates/swarm.ingress.yaml
- swarm/values.yaml
swarm: allow using the default nginx certificate by enabling tls but leaving acme disabled.
> Allow using default tls certficiates provided by the ingress controller

- smoke/templates/smoke.cronjob.yaml
- smoke/values.yaml
Abstracting away all the extra flags we pass to `swarm-smoke` and making the cronjob configurable directly from the `yaml` override.
> smoke cron job: generic extra flags

- swarm-private/templates/bootnode.statefulset.yaml
- swarm-private/templates/swarm.statefulset.yaml
- swarm-private/values.yaml
Switching `bootnode` with `swarm --bootnode-mode`, so that our bootnodes actually run the `hive` protocol, and discovery in Swarm works with `hive`, rather than with the `p2p` discovery functionality.
> swarm-private chart: change bootnode to swarm bootnode

- swarm-private/Chart.yaml
- swarm-private/templates/swarm.statefulset.yaml
- swarm/Chart.yaml
- swarm/templates/swarm.statefulset.yaml
This is incompatible with older versions of swarm. Therefore bumping the chart version so that we can still use version 0.0.1 of the chart to test the older binaries.
> swarm: new metrics flag that allows setting multiple tags

- swarm-private/templates/swarm.statefulset.yaml
- swarm/templates/swarm.statefulset.yaml
Note that I'm only using the 7 first bytes of the bzzkey and 10 first bytes of the pubkey. 
I'm happy to change this if desired.
> swarm: use bzzkey and pubkey as influxdb tags

- smoke/values.yaml
Related to https://github.com/ethersphere/go-ethereum/issues/1202
Image split PR: https://github.com/ethereum/go-ethereum/pull/19038
> smoke: use new docker repo

- swarm-global-store/.helmignore
- swarm-global-store/Chart.yaml
- swarm-global-store/README.md
- swarm-global-store/templates/_helpers.tpl
- swarm-global-store/templates/globalstore.service.yaml
- swarm-global-store/templates/globalstore.statefulset.yaml
- swarm-global-store/values.yaml
This chart deploys a [global-store](https://github.com/ethereum/go-ethereum/tree/master/cmd/swarm/global-store) that can be used by Swarm nodes to store their data at a central place. This is mainly useful for debugging and testing purposes. By default it will run in-memory, you can also choose to persist data to disk. See values.yaml for more details.
Swarm nodes that want to use this globalstore should run with the `--globalstore-api ` flag . E.g.: `--globalstore-api=ws://swarm-global-store:3033`
> Add global-store chart

- swarm-tests/.helmignore
- swarm-tests/Chart.yaml
- swarm-tests/README.md
- swarm-tests/scripts/run-tests.sh
- swarm-tests/templates/_helpers.tpl
- swarm-tests/templates/scripts.configmap.yaml
- swarm-tests/templates/tests.cronjob.yaml
- swarm-tests/values.yaml
Issue: https://github.com/ethersphere/go-ethereum/issues/1236
This chart is used to execute go tests against the swarm codebase.
A cronjob will be created and will fetch whatever version you define and execute tests against the codebase.
Have a look at the `values.yaml` file to check the default values. You can easily set the version and the command that you want to use for testing. See the example below:
```yaml
test:
config:
version: master
command: go test -v ./swarm/... -longrunning true
```
> Add chart that periodically runs tests against the swarm codebase

- swarm-private/templates/swarm.ingress.yaml
- swarm-private/templates/swarm.service.yaml
- swarm-private/values.yaml
- swarm/templates/swarm.ingress.yaml
- swarm/templates/swarm.service.yaml
- swarm/values.yaml
Requested via https://github.com/ethersphere/go-ethereum/issues/1220 
When enabled, your ingress resources targeting individual nodes, will have the websocket RPC API accessible via `/wsrpc`
Example of a request targeting a swarm node: 
```
echo '{"jsonrpc":"2.0","method":"admin_peers","id":1}' | websocat wss://swarm-private-0-yournamespace.stg.swarm-gateways.net/wsrpc --origin localhost
```
Example `values.yaml` file that enables the ws APIs and exposes them at the ingress level.
```yaml
swarm:
metricsEnabled: true
tracingEnabled: true
profilingEnabled: false
image:
repository: ethdevops/swarm
tag: edge
terminationGracePeriodSeconds: 5
imagePullPolicy: IfNotPresent
podManagementPolicy: Parallel
updateStrategy:
type: "OnDelete"
config:
ens_api: http://mainnet-geth-geth.geth:8545 …
```
> swarm: allow exposing websocket rpc api for testing purposes

- swarm-private/values.yaml
- swarm/values.yaml
Currently when running with tracing enabled, the Jaeger Query service is being exposed via `NodePort` by default. This should not be the case.
> jaeger-query: don't expose query service with NodePort

- swarm-private/templates/bootnode.statefulset.yaml
- swarm-private/templates/swarm.statefulset.yaml
- swarm-private/values.yaml
- swarm/templates/swarm.statefulset.yaml
- swarm/values.yaml
I've removed the "release-timestamp" annotation. I've changed my mind and this shouldn't be done like this.
If a client want's to trigger a deployment, this can be done by using the image hash or by updating a custom annotation.
This also brings the benefit of allowing us to use custom annotations on our pods. For example `fluentbit.io/exclude: "true"` would disable log forwarding to elasticsearch.
> Swarm: pod annotations

- kapacitor-importer/.helmignore
- kapacitor-importer/Chart.yaml
- kapacitor-importer/README.md
- kapacitor-importer/templates/_helpers.tpl
- kapacitor-importer/templates/configmap.batchscripts.yaml
- kapacitor-importer/templates/configmap.init.yaml
- kapacitor-importer/templates/configmap.streamscripts.yaml
- kapacitor-importer/templates/job.yaml
- kapacitor-importer/values.yaml
**This is a pre-requirement for setting up alerts on our swarm metrics** : https://github.com/ethersphere/go-ethereum/issues/1251 
This chart is used to run a job that imports batch or stream .tick scripts into an exising kapacitor instance.
For more information, check the default [`values.yaml`](values.yaml). You need to overwrite the `kapacitorURL` to point to your kapacitor service.
The following is an example on how you can create your own batch script:
```yaml
kapacitorUrl: http://your-kapacitor-service:9092
batchScripts:
cpu_alert.tick: |-
dbrp "telegraf"."autogen"
batch
|query('''
SELECT mean(usage_idle)
FROM "telegraf"."autogen"."cpu"
''')
.period(5m)
.every(5m)
.groupBy(time(1m), 'cpu')
|alert()
.crit(lambda: "mean" < 70)
.log('/tmp/batch_alerts.log')
```
> add kapacitor script importer

- swarm-private/templates/bootnode.service-headless.yaml
- swarm-private/templates/bootnode.statefulset.yaml
- swarm-private/templates/swarm.statefulset.yaml
This was not complying with the NetworkPolicy.
> swarm-private: fix bootnode port to be the same as on swarm nodes

- jaeger/templates/jaeger.deployment.yaml
- jaeger/values.yaml
This will become useful when we want to use another backend for storage (e.g. elasticsearch).
> jaeger: allow setting env vars

- jaeger/Chart.yaml
- jaeger/templates/jaeger-collector.service.yaml
- jaeger/values.yaml
By exposing the collector service, we can start running multiple jaeger agents that run close to the applications and use those to send the spans via `gRPC` to the collector service.
The idea is that we'll start running the jaeger agents within the swarm pods and have them sending the spans via `gRPC` to the jaeger collector.
> Jaeger: add collector service

- swarm-private/templates/bootnode.statefulset.yaml
- swarm-private/templates/swarm.statefulset.yaml
- swarm/templates/swarm.statefulset.yaml
These properties were ending up under `volumeClaimTemplates` when the persistence was set to `true`.
Should be under `sts.spec.template.spec`.
> swarm: fix nodeSelector, affinity and tolerations

- swarm-private/templates/swarm.statefulset.yaml
- swarm/templates/swarm.statefulset.yaml
No need to use `sh`. Currently it's showing: 
```
sh: can't open 'swarm': No such file or directory
```
This change should fix the problem since the swarm binary is already inside the PATH.
> swarm/swarm-private: fix influxdb tags

- swarm-private/templates/swarm.statefulset.yaml
- swarm/Chart.yaml
- swarm/requirements.lock
- swarm/requirements.yaml
- swarm/templates/bootnode.secret.yaml
- swarm/templates/bootnode.service-headless.yaml
- swarm/templates/bootnode.statefulset.yaml
- swarm/templates/podflags.configmap.yaml
- swarm/templates/swarm.statefulset.yaml
- swarm/values.yaml
These changes are relevant to the swarm chart (public cluster that exposes the swarm nodes).
- Update jaeger
- Added the pod specific flags option
- Added option to start a bootnode. Useful when deploying a public testnet. 
For now the bootnode is not exposed to the outside because it doesn't seem to be required.
All the other swarm nodes are exposed via public IPs and these can be used as bootnodes by clients that want to connect to the test cluster.
> swarm: new 0.0.5 version with bootnode and pod specific flags

- geth/values.yaml
fixes https://github.com/ethersphere/helm-charts/issues/1
> geth: use localhost for default rpc cors domains

- geth/Chart.yaml
- geth/templates/ethstats.deployment.yaml
- jaeger/Chart.yaml
- jaeger/templates/jaeger.deployment.yaml
`apps/v1beta2` has been deprecated on Kubernetes v1.16.
A followup PR will exist for the swarm charts, to update the jaeger dependency. 
Related to https://github.com/ethersphere/helm-charts/issues/104
> geth, jaeger: use stable apis 

- swarm-private/Chart.yaml
- swarm-private/requirements.lock
- swarm-private/requirements.yaml
- swarm/Chart.yaml
- swarm/requirements.lock
- swarm/requirements.yaml
fixes https://github.com/ethersphere/helm-charts/issues/104 
Jaeger dependency has been updated to use `apps/v1` instead of `apps/v1beta2`.
> swarm:  update jaeger deployment to use apps/v1 
